### ISSUE TITLE
Phaser.Events.EventEmitter not extending from EventEmitter

### ISSUE THREAD

**Issue by patrickgalbraith** [troyedwardsjr/phaser3-tsd#2]
If you look at the definition for `Phaser.Events.EventEmitter` it is missing a number of methods such as `on`, `off`, `emit`, etc... which are defined by the global EventEmitter.

**Comment by troyedwardsjr** [comment]
https://github.com/troyedwardsjr/phaser3-tsd/commit/b2764660b136ab8a59272d2148c9ffde37e6d858
