### ISSUE TITLE
Spritesheet in Phaser.Loader.LoaderPlugin

### ISSUE THREAD

**Issue by digitsensitive** [troyedwardsjr/phaser3-tsd#3]
hello! thanks for your work, it is great.
i wanted to load a spritesheet using this.load.spritesheet, which did not work. I looked at the phaser.d.ts file and did see that this was missing.

Would be nice to have it included.

    /**
     * Adds a Spritesheet to the current load queue.
     * 
     * 
     * 
     * Note: This method will only be available if the Spritesheet File type has been built into Phaser.
     * 
     * 
     * 
     * The file is **not** loaded immediately after calling this method.
     * 
     * Instead, the file is added to a queue within the Loader, which is processed automatically when the Loader starts.
     * @param key [description]
     * @param url [description]
     * @param config [description]
     * @param xhrSettings [description]
     */
    spritesheet(key: string, url: string, config: object, xhrSettings?: Phaser.Loader.XHRSettings): Phaser.Loader.LoaderPlugin;

**Comment by troyedwardsjr** [comment]
https://github.com/troyedwardsjr/phaser3-tsd/commit/b2764660b136ab8a59272d2148c9ffde37e6d858
