### ISSUE TITLE
RectangleToRectangle

### ISSUE THREAD

**Issue by digitsensitive** [troyedwardsjr/phaser3-tsd#4]
Hello!

function RectangleToRectangle is missing the object type. Getting following error:

```
TS2345: Argument of type 'object | Rectangle' is not assignable to parameter of type 'Rectangle'.
Type 'object' is not assignable to type 'Rectangle'. Property 'x' is missing in type '{}'.
```

The function should be like this, then it works:

function RectangleToRectangle(rectA: Phaser.Geom.Rectangle **| object**, rectB: Phaser.Geom.Rectangle **| object**): boolean;

Thanks for fixing!

**Comment by troyedwardsjr** [comment]
https://github.com/troyedwardsjr/phaser3-tsd/commit/bca063bb8bfcc742cee9447dadb2c23aedadca9a
